# Generated by Django 5.0.1 on 2024-02-29 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='place_born',
            new_name='place_birth',
        ),
    ]
